package demo.server.common.enums;

public enum NotificationType {
    QR_LOGIN_SUCCESS,
    SESSION_STARTED,
    SESSION_ENDING,
    SMART_STATION_SUCCESS,
    SMART_STATION_PARTIAL_FAILURE,
    TEAM_INVITATION,
    LOBBY_UPDATE,
    ORDER_NEW,
    ORDER_ACCEPTED,
    ORDER_PREPARING,
    ORDER_READY,
    ORDER_DELIVERED,
    DEVICE_ALERT,
    ACCOUNT_SECURITY,
    SYSTEM
}
